# Generated by Django 5.2.7 on 2025-11-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=90, verbose_name='Full name')),
                ('avatar', models.FileField(upload_to='', verbose_name='Аватар')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.owner')),
            ],
        ),
    ]
