# Generated by Django 5.2.7 on 2025-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
